language: node_js
node_js:
    - '10'
cache: yarn
before_deploy:
    - 'npm run build'
deploy:
    provider: pages
    local-dir: build
    skip-cleanup: true
    github-token: $SECRET_GH_PAGE_TOKEN
    keep-history: true
    on:
        branch: master
