import React from 'react'
import styled from 'styled-components'
import map from 'ramda/src/map'
import compose from 'ramda/src/compose'
import addIndex from 'ramda/src/addIndex'
import pluck from 'ramda/src/pluck'
import sum from 'ramda/src/sum'
import { CloseButton } from '../../../../Shared/Components/Controls'

import { colors } from '../../../../utils/color-palette'

const indexedMap = addIndex(map)

const FixedDiv = styled.div`
  width: 100%;
  max-width: 800px;
  min-width: 320px;
  box-sizing: border-box;
  position: fixed;
  display: flex;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: white;
  padding: 10px;
  flex-direction: column;
  box-shadow: 0px 0px 1px 2px rgba(0, 0, 0, 0.2);
  border-radius: 2px;
  z-index: 100;
`

const Header = styled.header`
  text-align: center;
  border-bottom: 3px solid ${colors.primaryColor};
  margin-bottom: 10px;
  line-height: 2rem;
`

const Story = styled.article`
  margin: 10px 0px;
  border-bottom: 1px solid lightgrey;
  padding: 10px 20px;
  & header {
    line-height: 1.4rem;
    font-size: 1.2rem;
    display: flex;
    justify-content: space-between;
    padding-bottom: 10px;
    & span:first-child {
      font-weight: bold;
    }
  }
`

const Description = styled.section`padding: 0px 20px;`

const Footer = styled.footer`
  font-size: 0.8rem;
  text-align: right;
  padding: 0px 20px;
`

const showTotalScore = compose(sum, pluck('score'))

export const Report = ({ game, stories, onClose }) => {
  const displayStory = indexedMap((st, idx) => {
    return (
      <Story key={idx}>
        <header>
          <span>
            {st.title}
          </span>
          <span>
            {st.score}
          </span>
        </header>
        <div>
          {st.description}
        </div>
      </Story>
    )
  })
  return (
    <FixedDiv>
      <CloseButton onClick={() => onClose()} topRight />
      <Header>
        <h1>
          Report for "{game.title}"
        </h1>
      </Header>
      <Description>
        {game.description}
      </Description>
      <section>
        {displayStory(stories)}
      </section>
      <div>
        <Story>
          <header>
            <span>Total Score</span>
            <span>
              {showTotalScore(stories)}
            </span>
          </header>
        </Story>
      </div>
      <Footer>Report generated By FreePlanningPoker</Footer>
    </FixedDiv>
  )
}
