import React from 'react';
import compose from 'ramda/src/compose';
import pluck from 'ramda/src/pluck';
import sum from 'ramda/src/sum';
import { Modal, Button, Table } from 'antd';
import { comparator } from '../Deck/deck';

const showTotalScore = compose(
    sum,
    pluck('score'),
);

export const Report = ({ game, stories, onClose }) => {
    const columns = [
        {
            title: 'Story Tile',
            dataIndex: 'title',
            sorter: (a, b) => a.title.localeCompare(b.title),
        },
        {
            title: 'Description',
            dataIndex: 'description',
        },
        {
            title: 'Story Points',
            dataIndex: 'score',
            defaultSortOrder: 'descend',
            sorter: (a, b) => comparator(a.score, b.score),
        },
    ];
    const dataSource = stories.map((story, index) => ({ ...story, key: index }));

    return (
        <Modal
            visible={true}
            title={`Report for "${game.title}"`}
            footer={[
                <Button onClick={onClose} key="ok-button">
                    Ok
                </Button>,
            ]}
            onCancel={onClose}
            width="800px"
        >
            <Table
                dataSource={dataSource}
                columns={columns}
                title={() => `Total Score ${showTotalScore(stories)}`}
                footer={() => `Report generated By FreePlanningPoker`}
            />
        </Modal>
    );
};
